paths:
  - '**/test/**'
  - '**/tests/**'
  - '**/*_test.py'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/examples/**'
  - '**/fixtures/**'
  - '**/conftest.py'
  - '**/mocks/**'
  - '**/stubs/**'
  - '**/.venv/**'
  - '**/venv/**'
  - '**/env/**'
  - '**/node_modules/**'
  - '**/__pycache__/**'

patterns:
  - term: "test_key"
    reason: "Test fixture key"
  - term: "mock_secret"
    reason: "Mock secret for testing"
  - term: "example-api-key"
    reason: "Documentation example"
  - term: "test_"
    reason: "Test pattern prefix"
