import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { API_BASE } from '../lib/api';

interface HistoricalForecastItem {
  forecast_id: string;
  region_name: string;
  latitude: number;
  longitude: number;
  forecast_date: string;
  forecast_horizon: number;
  model_type: string;
  sources: string[];
  accuracy_score?: number;
}

export default function HistoryPage() {
  const [history, setHistory] = useState<HistoricalForecastItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [limit, setLimit] = useState(50);
  const [regionFilter, setRegionFilter] = useState('');

  useEffect(() => {
    const fetchHistory = async () => {
      setLoading(true);
      setError(null);

      try {
        const params = new URLSearchParams({ limit: limit.toString() });
        if (regionFilter.trim()) {
          params.append('region_name', regionFilter.trim());
        }

        const response = await fetch(`${API_BASE}/api/forecasting/history?${params.toString()}`);

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        const data = await response.json();
        if (!Array.isArray(data)) {
          throw new Error('Invalid response format');
        }

        setHistory(data);
      } catch (e) {
        console.error('Failed to fetch forecast history:', e);
        setError('Failed to load forecast history');
        setHistory([]);
      } finally {
        setLoading(false);
      }
    };

    fetchHistory();
  }, [limit, regionFilter]);

  const formatDate = (dateString: string) => {
    try {
      const date = new Date(dateString);
      return date.toLocaleString();
    } catch {
      return dateString;
    }
  };

  return (
    <>
      <Head>
        <title>Forecast History - Behavior Convergence Explorer</title>
        <meta name="description" content="View historical forecast records" />
      </Head>
      <main style={{ fontFamily: 'system-ui, sans-serif', padding: 24, maxWidth: 1200, margin: '0 auto' }}>
        <h1>Forecast History</h1>
        <p style={{ color: '#555', marginBottom: 24 }}>
          View historical forecasts generated by the system.
        </p>

        <nav style={{ marginBottom: 32, display: 'flex', gap: 16 }}>
          <Link href="/forecast" style={{ textDecoration: 'underline', color: '#0070f3' }}>
            Generate Forecast
          </Link>
          <Link href="/playground" style={{ textDecoration: 'underline', color: '#0070f3' }}>
            Live Playground
          </Link>
          <Link href="/live" style={{ textDecoration: 'underline', color: '#0070f3' }}>
            Live Monitoring
          </Link>
          <Link href="/" style={{ textDecoration: 'underline', color: '#0070f3' }}>
            Results Dashboard
          </Link>
          <Link href="/history" style={{ textDecoration: 'underline', color: '#0070f3', fontWeight: 'bold' }}>
            Forecast History
          </Link>
        </nav>

        <div style={{ marginBottom: 24, display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span>Limit:</span>
            <select
              data-testid="history-limit-select"
              value={limit}
              onChange={(e) => setLimit(Number(e.target.value))}
              style={{ padding: '4px 8px', border: '1px solid #ddd', borderRadius: 4 }}
            >
              <option value={20}>20</option>
              <option value={50}>50</option>
              <option value={100}>100</option>
            </select>
          </label>
          <label style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span>Filter by region:</span>
            <input
              data-testid="history-region-filter"
              type="text"
              value={regionFilter}
              onChange={(e) => setRegionFilter(e.target.value)}
              placeholder="Region name..."
              style={{ padding: '4px 8px', border: '1px solid #ddd', borderRadius: 4, minWidth: 200 }}
            />
          </label>
        </div>

        {error && (
          <section
            style={{
              padding: 16,
              backgroundColor: '#f8d7da',
              color: '#721c24',
              borderRadius: 4,
              marginBottom: 24,
            }}
          >
            <strong>Error:</strong> {error}
          </section>
        )}

        {loading ? (
          <p data-testid="history-loading">Loading forecast history...</p>
        ) : (
          <div data-testid="forecast-history-container">
            {history.length === 0 ? (
              <p>No forecast history found.</p>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table
                  data-testid="forecast-history-table"
                  style={{ borderCollapse: 'collapse', minWidth: 800, width: '100%' }}
                >
                  <thead>
                    <tr>
                      <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                        Region
                      </th>
                      <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                        Forecast Date
                      </th>
                      <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                        Horizon (days)
                      </th>
                      <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                        Model
                      </th>
                      <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                        Sources
                      </th>
                      {history.some((h) => h.accuracy_score !== undefined && h.accuracy_score !== null) && (
                        <th style={{ borderBottom: '1px solid #ddd', textAlign: 'left', padding: '8px 12px' }}>
                          Accuracy
                        </th>
                      )}
                    </tr>
                  </thead>
                  <tbody>
                    {history.map((item, index) => (
                      <tr
                        key={item.forecast_id || `history-${index}`}
                        data-testid="forecast-history-row"
                        style={{ borderBottom: '1px solid #f0f0f0' }}
                      >
                        <td style={{ padding: '8px 12px' }}>{item.region_name}</td>
                        <td style={{ padding: '8px 12px', fontFamily: 'ui-monospace, monospace' }}>
                          {formatDate(item.forecast_date)}
                        </td>
                        <td style={{ padding: '8px 12px', textAlign: 'center' }}>{item.forecast_horizon}</td>
                        <td style={{ padding: '8px 12px' }}>{item.model_type}</td>
                        <td style={{ padding: '8px 12px' }}>
                          {item.sources && item.sources.length > 0 ? item.sources.join(', ') : 'N/A'}
                        </td>
                        {history.some((h) => h.accuracy_score !== undefined && h.accuracy_score !== null) && (
                          <td style={{ padding: '8px 12px', textAlign: 'right' }}>
                            {item.accuracy_score !== undefined && item.accuracy_score !== null
                              ? item.accuracy_score.toFixed(3)
                              : 'N/A'}
                          </td>
                        )}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </main>
    </>
  );
}
